name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # يمكنك تحديد إصدار معين مثل 3.24.3

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze the project
      - name: Analyze project
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
